name: body_optimizer
description: Workout app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_time_picker_spinner: ^2.0.0
  persistent_bottom_nav_bar: ^5.0.2
  flutter_launcher_icons: ^0.10.0
  animated_splash_screen: ^1.3.0
  elegant_notification: ^1.6.4
  cupertino_icons: ^1.0.5
  table_calendar: ^3.0.8
  path_provider: ^2.0.11
  flutter_lints: ^2.0.1
  direct_select: ^2.0.0
  getwidget: ^3.0.1
  lottie: ^2.0.0
  intl: ^0.17.0
  google_fonts:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/body_optimizer_android.png"

flutter:
  assets:
    - assets/
  uses-material-design: true
