name: body_optimizer
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.3.0
  cupertino_icons: ^1.0.5
  google_fonts:
  table_calendar: ^3.0.8
  persistent_bottom_nav_bar: ^5.0.2
  getwidget: ^3.0.1
  intl: ^0.17.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/body_optimizer_android.png"

flutter:
  assets:
    - assets/images/
  uses-material-design: true
