name: body_optimizer
description: Workout app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_time_picker_spinner: ^2.0.0
  flutter_launcher_icons: ^0.11.0
  animated_splash_screen: ^1.3.0
  elegant_notification: ^1.6.4
  table_calendar: ^3.0.8
  flutter_lints: ^2.0.1
  direct_select: ^2.0.0
  getwidget: ^3.0.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts:
  intl:
  persistent_bottom_nav_bar: ^5.0.2
  get:
  modal_bottom_sheet:
  video_player:
  dropdown_button2: ^1.8.9
  path_provider: ^2.0.11
  lottie: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/body_optimizer_android.png"

flutter:
  assets:
    - assets/images/
    - assets/animations/
    - assets/videos/
    - textFiles/
    - animation/
  uses-material-design: true
